
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const SEARCH_CONNECTION_SUCCESS = "SEARCH_CONNECTION_SUCCESS"
export const SEARCH_CONNECTION_FAIL = "SEARCH_CONNECTION_FAIL"

export const BOOK_SUCCESS = "BOOK_SUCCESS"
export const BOOK_FAIL = "BOOK_FAIL"