# Generated by Django 3.2.4 on 2021-09-02 15:15

from django.db import migrations, models
import enumchoicefield.fields
import order.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='unknown', max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('zip_code', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('apartment', models.CharField(blank=True, default='', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='unknown', max_length=255, null=True)),
                ('total_cost', models.FloatField(blank=True, default=0.0, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('amount', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('payment_method', models.CharField(default='Card', max_length=280, null=True)),
                ('updated_by', models.CharField(default='System', max_length=200, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='System', max_length=280, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_status', enumchoicefield.fields.EnumChoiceField(default=order.enums.OrderStatusEnum(4), enum_class=order.enums.OrderStatusEnum, max_length=18)),
                ('products', models.ManyToManyField(blank=True, default='', related_name='order', to='product.ProductModel')),
                ('shipping', models.ManyToManyField(blank=True, default='', related_name='order', to='order.ShippingModel')),
            ],
        ),
    ]
