# Generated by Django 3.2.4 on 2021-07-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20210704_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_mediator',
            new_name='is_moderator',
        ),
    ]
