# Generated by Django 3.2.4 on 2021-07-24 20:24

from django.db import migrations, models
import identity.models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_rename_is_mediator_useraccount_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=identity.models.upload_to),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
