# Generated by Django 3.2.4 on 2021-07-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20210724_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created_by',
            field=models.CharField(default='System', max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updated_by',
            field=models.CharField(default='System', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
