# Generated by Django 3.2.4 on 2021-07-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_auto_20210726_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_reporter',
        ),
    ]
