# Generated by Django 3.2.4 on 2021-08-01 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_merchantmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmodel',
            name='merchant',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
