# Generated by Django 3.2.4 on 2021-08-02 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_alter_merchantmodel_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantmodel',
            name='merchant',
        ),
        migrations.AddField(
            model_name='merchantmodel',
            name='merchant',
            field=models.ManyToManyField(blank=True, default='', related_name='user_merchant', to=settings.AUTH_USER_MODEL),
        ),
    ]
