
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS"
export const GET_ALL_ORDER_FAIL = "GET_ALL_ORDER_FAIL"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL"