# Generated by Django 3.2.4 on 2021-09-02 15:15

from django.db import migrations, models
import enumchoicefield.fields
import product.enums
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=product.models.upload_to)),
                ('updated_by', models.CharField(default='System', max_length=200, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='System', max_length=280, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('product_status', enumchoicefield.fields.EnumChoiceField(default=product.enums.ProductStatusEnum(1), enum_class=product.enums.ProductStatusEnum, max_length=13)),
                ('market_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('customer_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('rating_sum', models.FloatField(blank=True, default=0.0, null=True)),
                ('raters_sum', models.BigIntegerField(blank=True, default=0.0, null=True)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('product_type', models.ManyToManyField(blank=True, default='', related_name='product', to='product.ProductTypeModel')),
                ('product_unit', models.ManyToManyField(blank=True, default='', related_name='product', to='product.ProductUnitModel')),
            ],
        ),
    ]
