# Generated by Django 3.2.4 on 2021-09-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('de', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('fr', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('it', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('ar', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('am', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('ti', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producttypemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='am',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='ar',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='de',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='en',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='fr',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='it',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='ti',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name',
            field=models.ManyToManyField(blank=True, default='', related_name='product', to='product.ProductNameModel'),
        ),
    ]
