# Generated by Django 3.2.4 on 2021-09-10 14:22

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210905_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=product.models.upload_slider_to)),
            ],
        ),
    ]
