version: "3.3"

services:
  db:
    image: postgres
    restart: always #Prevent postgres from stopping the container
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/backend/server/django_static
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
    static_volume: { }

